In [1]:

# from pyspark.sql import SparkSession

# spark = SparkSession.builder \
#     .appName("RetailPipeline") \
#     .master("local[*]") \
#     .getOrCreate()

ERROR StatusLogger Reconfiguration failed: No configuration found for '5c29bfd' at 'null' in 'null'
ERROR StatusLogger Reconfiguration failed: No configuration found for 'Default' at 'null' in 'null'
26/04/20 22:32:51 WARN Utils: Your hostname, YTuSurface5 resolves to a loopback address: 127.0.1.1; using 10.255.255.254 instead (on interface lo)
26/04/20 22:32:51 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
26/04/20 22:32:52 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable

In [1]:
# need install delta spark - version compatibal e.g. spark 3.5.x with delta spark v3.X
# need to set up hive meta store

from pyspark.sql import SparkSession
from delta import configure_spark_with_delta_pip

builder = SparkSession.builder \
    .appName("retail_pipeline") \
    .master("local[*]") \
    .config("spark.sql.extensions", "io.delta.sql.DeltaSparkSessionExtension") \
    .config("spark.sql.catalog.spark_catalog", "org.apache.spark.sql.delta.catalog.DeltaCatalog")

spark = configure_spark_with_delta_pip(builder).getOrCreate()

ERROR StatusLogger Reconfiguration failed: No configuration found for '5c29bfd' at 'null' in 'null'
ERROR StatusLogger Reconfiguration failed: No configuration found for 'Default' at 'null' in 'null'
26/04/22 14:05:33 WARN Utils: Your hostname, YTuSurface5 resolves to a loopback address: 127.0.1.1; using 10.255.255.254 instead (on interface lo)
26/04/22 14:05:33 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address

:: loading settings :: url = jar:file:/home/yiqingtu/spark/spark-3.5.5-bin-hadoop3/jars/ivy-2.5.1.jar!/org/apache/ivy/core/settings/ivysettings.xml

Ivy Default Cache set to: /home/yiqingtu/.ivy2/cache
The jars for the packages stored in: /home/yiqingtu/.ivy2/jars
io.delta#delta-spark_2.12 added as a dependency
:: resolving dependencies :: org.apache.spark#spark-submit-parent-f714acfe-36d8-4d89-ba9a-11154097c68e;1.0
	confs: [default]
	found io.delta#delta-spark_2.12;3.2.0 in central
	found io.delta#delta-storage;3.2.0 in central
	found org.antlr#antlr4-runtime;4.9.3 in central
:: resolution report :: resolve 163ms :: artifacts dl 6ms
	:: modules in use:
	io.delta#delta-spark_2.12;3.2.0 from central in [default]
	io.delta#delta-storage;3.2.0 from central in [default]
	org.antlr#antlr4-runtime;4.9.3 from central in [default]
	---------------------------------------------------------------------
	|                  |            modules            ||   artifacts   |
	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
	---------------------------------------------------------------------
	|      default     |   3   |   0   |   0   |   0   ||   3   |   0   |
	---------------------------------------------------------------------
:: retrieving :: org.apache.spark#spark-submit-parent-f714acfe-36d8-4d89-ba9a-11154097c68e
	confs: [default]
	0 artifacts copied, 3 already retrieved (0kB/8ms)
26/04/22 14:05:34 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).

In [2]:


file_name = "../data/raw/orders/"

df = spark.read.csv(file_name, header=True, inferSchema=True)

df.limit(1000).toPandas()

,row_id,order_id,order_date,ship_date,ship_mode,customer_id,customer_name,segment,country,city,...,postal_code,region,product_id,category,subcategory,product_name,sales,quantity,discount,profit
0,764,CA-2014-162775,2014-01-13,2014-01-15,Second Class,CS-12250,Chris Selesnick,Corporate,United States,Bossier City,...,71111,South,OFF-EN-10001990,Office Supplies,Envelopes,Staple envelope,11.36,2.000,0.00,5.3392
1,765,CA-2014-162775,2014-01-13,2014-01-15,Second Class,CS-12250,Chris Selesnick,Corporate,United States,Bossier City,...,71111,South,OFF-EN-10001532,Office Supplies,Envelopes,Brown Kraft Recycled Envelopes,50.94,3.000,0.00,25.4700
2,766,CA-2014-162775,2014-01-13,2014-01-15,Second Class,CS-12250,Chris Selesnick,Corporate,United States,Bossier City,...,71111,South,TEC-AC-10003174,Technology,Accessories,Plantronics S12 Corded Telephone Headset System,646.74,6.000,0.00,258.6960
3,767,CA-2014-162775,2014-01-13,2014-01-15,Second Class,CS-12250,Chris Selesnick,Corporate,United States,Bossier City,...,71111,South,OFF-BI-10004187,Office Supplies,Binders,3-ring staple pack,5.64,3.000,0.00,2.7072
4,768,CA-2014-162775,2014-01-13,2014-01-15,Second Class,CS-12250,Chris Selesnick,Corporate,United States,Bossier City,...,71111,South,OFF-ST-10000025,Office Supplies,Storage,Fellowes Stor/Drawer Steel Plus Storage Drawers,572.58,6.000,0.00,34.3548
5,2979,CA-2014-109232,2014-01-13,2014-01-16,Second Class,ND-18370,Natalie DeCherney,Consumer,United States,Mount Pleasant,...,29464,South,FUR-CH-10000422,Furniture,Chairs,Global Highback Leather Tilter in Burgundy,545.94,6.000,0.00,87.3504
6,4938,CA-2014-157147,2014-01-13,2014-01-18,Standard Class,BD-11605,Brian Dahlen,Consumer,United States,San Francisco,...,94109,West,OFF-ST-10000078,Office Supplies,Storage,Tennsco 6- and 18-Compartment Lockers,1325.85,5.000,0.00,238.6530
7,4939,CA-2014-157147,2014-01-13,2014-01-18,Standard Class,BD-11605,Brian Dahlen,Consumer,United States,San Francisco,...,94109,West,FUR-BO-10003034,Furniture,Bookcases,"O'Sullivan Elevations Bookcase, Cherry Finish",333.999,3.000,0.15,3.9294
8,4940,CA-2014-157147,2014-01-13,2014-01-18,Standard Class,BD-11605,Brian Dahlen,Consumer,United States,San Francisco,...,94109,West,OFF-AR-10003514,Office Supplies,Art,4009 Highlighters by Sanford,19.9,5.000,0.00,6.5670
9,9629,CA-2014-118192,2014-01-13,2014-01-18,Standard Class,MM-17920,Michael Moore,Consumer,United States,Newark,...,43055,East,OFF-PA-10002947,Office Supplies,Paper,Xerox 1923,37.408,7.000,0.20,13.0928
10,9630,CA-2014-118192,2014-01-13,2014-01-18,Standard Class,MM-17920,Michael Moore,Consumer,United States,Newark,...,43055,East,OFF-BI-10003476,Office Supplies,Binders,Avery Metallic Poly Binders,3.438,2.000,0.70,-2.5212
11,5328,CA-2014-130813,2014-01-06,2014-01-08,Second Class,LS-17230,Lycoris Saunders,Consumer,United States,Los Angeles,...,90049,West,OFF-PA-10002005,Office Supplies,Paper,Xerox 225,19.44,3.000,0.00,9.3312
12,7181,CA-2014-106054,2014-01-06,2014-01-07,First Class,JO-15145,Jack O'Briant,Corporate,United States,Athens,...,30605,South,OFF-AR-10002399,Office Supplies,Art,"Dixon Prang Watercolor Pencils, 10-Color Set w...",12.78,3.000,0.00,5.2398
13,7475,CA-2014-167199,2014-01-06,2014-01-10,Standard Class,ME-17320,Maria Etezadi,Home Office,United States,Henderson,...,42420,South,FUR-CH-10004063,Furniture,Chairs,Global Deluxe High-Back Manager's Chair,2573.82,9.000,0.00,746.4078
14,7476,CA-2014-167199,2014-01-06,2014-01-10,Standard Class,ME-17320,Maria Etezadi,Home Office,United States,Henderson,...,42420,South,OFF-BI-10004632,Office Supplies,Binders,Ibico Hi-Tech Manual Binding System,609.98,2.000,0.00,274.4910
15,7477,CA-2014-167199,2014-01-06,2014-01-10,Standard Class,ME-17320,Maria Etezadi,Home Office,United States,Henderson,...,42420,South,OFF-AR-10001662,Office Supplies,Art,Rogers Handheld Barrel Pencil Sharpener,5.48,2.000,0.00,1.4796
16,7478,CA-2014-167199,2014-01-06,2014-01-10,Standard Class,ME-17320,Maria Etezadi,Home Office,United States,Henderson,...,42420,South,TEC-PH-10004977,Technology,Phones,GE 30524EE4,391.98,2.000,0.00,113.6742
17,7479,CA-2014-167199,2014-01-06,2014-01-10,Standard Class,ME-17320,Maria Etezadi,Home Office,United States,Henderson,...,42420,South,TEC-PH-10004539,Technology,Phones,Wireless Extenders zBoost YX545 SOHO Signal Bo...,755.96,4.000,0.00,204.1092
18,7480,CA-2014-167199,2014-01-06,2014-01-10,Standard Class,ME-17320,Maria Etezadi,Home Office,United States,Henderson,...,42420,South,OFF-FA-10001883,Office Supplies,Fasteners,"Alliance Super-Size Bands, Assorted Sizes",31.12,4.000,0.00,0.3112
19,7481,CA-2014-167199,2014-01-06,2014-01-10,Standard Class,ME-17320,Maria Etezadi,Home Office,United States,Henderson,...,42420,South,OFF-PA-10000955,Office Supplies,Paper,Southworth 25% Cotton Granite Paper & Envelopes,6.54,1.000,0.00,3.0084
20,740,CA-2014-112326,2014-01-04,2014-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-LA-10003223,Office Supplies,Labels,Avery 508,11.784,3.000,0.20,4.2717
21,741,CA-2014-112326,2014-01-04,2014-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-ST-10002743,Office Supplies,Storage,SAFCO Boltless Steel Shelving,272.736,3.000,0.20,-64.7748
22,742,CA-2014-112326,2014-01-04,2014-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-BI-10004094,Office Supplies,Binders,GBC Standard Plastic Binding Systems Combs,3.54,2.000,0.80,-5.4870
23,7661,CA-2014-105417,2014-01-07,2014-01-12,Standard Class,VS-21820,Vivek Sundaresam,Consumer,United States,Huntsville,...,77340,Central,FUR-FU-10004864,Furniture,Furnishings,"""Howard Miller 14-1/2"""" Diameter Chrome Round ...",76.728,3.000,0.60,-53.7096
24,7662,CA-2014-105417,2014-01-07,2014-01-12,Standard Class,VS-21820,Vivek Sundaresam,Consumer,United States,Huntsville,...,77340,Central,OFF-BI-10003708,Office Supplies,Binders,Acco Four Pocket Poly Ring Binder with Label H...,10.43,7.000,0.80,-18.2525
25,866,CA-2014-149020,2014-01-10,2014-01-15,Standard Class,AJ-10780,Anthony Jacobs,Corporate,United States,Springfield,...,22153,South,OFF-LA-10004272,Office Supplies,Labels,Avery 482,2.89,1.000,0.00,1.3583
26,867,CA-2014-149020,2014-01-10,2014-01-15,Standard Class,AJ-10780,Anthony Jacobs,Corporate,United States,Springfield,...,22153,South,FUR-FU-10000965,Furniture,Furnishings,"""Howard Miller 11-1/2"""" Diameter Ridgewood Wal...",51.94,1.000,0.00,21.2954
27,593,CA-2014-135405,2014-01-09,2014-01-13,Standard Class,MS-17830,Melanie Seite,Consumer,United States,Laredo,...,78041,Central,OFF-AR-10004078,Office Supplies,Art,Newell 312,9.344,2.000,0.20,1.1680
28,594,CA-2014-135405,2014-01-09,2014-01-13,Standard Class,MS-17830,Melanie Seite,Consumer,United States,Laredo,...,78041,Central,TEC-AC-10001266,Technology,Accessories,Memorex Micro Travel Drive 8 GB,31.2,3.000,0.20,9.7500
29,7981,CA-2014-103800,2014-01-03,2014-01-07,Standard Class,DP-13000,Darren Powers,Consumer,United States,Houston,...,77095,Central,OFF-PA-10000174,Office Supplies,Paper,"""Message Book, Wirebound, Four 5 1/2"""" X 4"""" F...","200 Dupl. Sets/Book""",16.448,2.00,0.2000
30,1760,CA-2014-141817,2014-01-05,2014-01-12,Standard Class,MB-18085,Mick Brown,Consumer,United States,Philadelphia,...,19143,East,OFF-AR-10003478,Office Supplies,Art,Avery Hi-Liter EverBold Pen Style Fluorescent ...,19.536,3.000,0.20,4.8840
31,6475,CA-2014-149524,2014-01-14,2014-01-15,First Class,BS-11590,Brendan Sweed,Corporate,United States,Philadelphia,...,19140,East,FUR-BO-10003433,Furniture,Bookcases,Sauder Cornerstone Collection Library,61.96,4.000,0.50,-53.2856
32,717,CA-2014-130092,2014-01-11,2014-01-14,First Class,SV-20365,Seth Vernon,Consumer,United States,Dover,...,19901,East,FUR-FU-10000010,Furniture,Furnishings,"DAX Value U-Channel Document Frames, Easel Back",9.94,2.000,0.00,3.0814

In [3]:
ls ./spark-warehouse/bronze_orders

_delta_log/
part-00000-72f35ae3-b75d-44ba-b574-3dfe6534d12d-c000.snappy.parquet
part-00001-e384ca78-788e-43a8-a411-8db0b084caee-c000.snappy.parquet
part-00002-a1054700-6282-4a8e-a5b0-4045cb90596e-c000.snappy.parquet
part-00003-c6e61258-2e79-46fa-92a9-6415aa4dc59a-c000.snappy.parquet
part-00004-d52b1ba2-e0c0-4285-9b4c-ef928842d055-c000.snappy.parquet
part-00005-e27fd37e-d408-447e-a696-563e54313110-c000.snappy.parquet
part-00006-4541a6c6-0b64-491c-bc0f-1e8c73cf9354-c000.snappy.parquet
part-00007-b0accb8b-f926-4617-b3a6-2301d0b35eeb-c000.snappy.parquet
part-00008-f2218eb3-8453-4635-a369-a2f8da5332fa-c000.snappy.parquet
part-00009-3de669a9-047c-43f3-9abf-8ba817b22bcb-c000.snappy.parquet

In [10]:
# df.write.format("delta") \
#   .mode("append") \
#   .save("./data/delta/bronze/orders")

# use path vs use register table - record in catalog

# df.write.format("delta").saveAsTable("bronze_orders")

bronze_orders = "../delta/bronze/orders"

df.write.format("delta") \
  .mode("overwrite") \
  .save(bronze_orders)

26/04/22 14:09:55 WARN SparkStringUtils: Truncated the string representation of a plan since it was too large. This behavior can be adjusted by setting 'spark.sql.debug.maxToStringFields'.

In [11]:
# test -> read delta table back 

# check count
# print schema
# check physical location use ls 

check_df = spark.read.load(bronze_orders)
check_df.limit(1000).toPandas()

,row_id,order_id,order_date,ship_date,ship_mode,customer_id,customer_name,segment,country,city,...,postal_code,region,product_id,category,subcategory,product_name,sales,quantity,discount,profit
0,764,CA-2014-162775,2014-01-13,2014-01-15,Second Class,CS-12250,Chris Selesnick,Corporate,United States,Bossier City,...,71111,South,OFF-EN-10001990,Office Supplies,Envelopes,Staple envelope,11.36,2.000,0.0,5.3392
1,765,CA-2014-162775,2014-01-13,2014-01-15,Second Class,CS-12250,Chris Selesnick,Corporate,United States,Bossier City,...,71111,South,OFF-EN-10001532,Office Supplies,Envelopes,Brown Kraft Recycled Envelopes,50.94,3.000,0.0,25.4700
2,766,CA-2014-162775,2014-01-13,2014-01-15,Second Class,CS-12250,Chris Selesnick,Corporate,United States,Bossier City,...,71111,South,TEC-AC-10003174,Technology,Accessories,Plantronics S12 Corded Telephone Headset System,646.74,6.000,0.0,258.6960
3,767,CA-2014-162775,2014-01-13,2014-01-15,Second Class,CS-12250,Chris Selesnick,Corporate,United States,Bossier City,...,71111,South,OFF-BI-10004187,Office Supplies,Binders,3-ring staple pack,5.64,3.000,0.0,2.7072
4,768,CA-2014-162775,2014-01-13,2014-01-15,Second Class,CS-12250,Chris Selesnick,Corporate,United States,Bossier City,...,71111,South,OFF-ST-10000025,Office Supplies,Storage,Fellowes Stor/Drawer Steel Plus Storage Drawers,572.58,6.000,0.0,34.3548
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61,7981,CA-2014-103800,2014-01-03,2014-01-07,Standard Class,DP-13000,Darren Powers,Consumer,United States,Houston,...,77095,Central,OFF-PA-10000174,Office Supplies,Paper,"""Message Book, Wirebound, Four 5 1/2"""" X 4"""" F...","200 Dupl. Sets/Book""",16.448,2.0,0.2000
62,6475,CA-2014-149524,2014-01-14,2014-01-15,First Class,BS-11590,Brendan Sweed,Corporate,United States,Philadelphia,...,19140,East,FUR-BO-10003433,Furniture,Bookcases,Sauder Cornerstone Collection Library,61.96,4.000,0.5,-53.2856
63,6475,CA-2014-149524,2014-01-14,2014-01-15,First Class,BS-11590,Brendan Sweed,Corporate,United States,Philadelphia,...,19140,East,FUR-BO-10003433,Furniture,Bookcases,Sauder Cornerstone Collection Library,61.96,4.000,0.5,-53.2856
64,717,CA-2014-130092,2014-01-11,2014-01-14,First Class,SV-20365,Seth Vernon,Consumer,United States,Dover,...,19901,East,FUR-FU-10000010,Furniture,Furnishings,"DAX Value U-Channel Document Frames, Easel Back",9.94,2.000,0.0,3.0814
65,717,CA-2014-130092,2014-01-11,2014-01-14,First Class,SV-20365,Seth Vernon,Consumer,United States,Dover,...,19901,East,FUR-FU-10000010,Furniture,Furnishings,"DAX Value U-Channel Document Frames, Easel Back",9.94,2.000,0.0,3.0814

In [12]:
check_df.count()

66

In [13]:



# ls ./data/delta/bronze/orders

In [14]:
check_df = spark.read.table("bronze_orders")

# need panda library
check_df.limit(1000).toPandas()

AnalysisException: [TABLE_OR_VIEW_NOT_FOUND] The table or view `bronze_orders` cannot be found. Verify the spelling and correctness of the schema and catalog.
If you did not qualify the name with a schema, verify the current_schema() output, or qualify the name with the correct schema and catalog.
To tolerate the error on drop use DROP VIEW IF EXISTS or DROP TABLE IF EXISTS.;
'UnresolvedRelation [bronze_orders], [], false

In [15]:
check_df.printSchema()

root
 |-- row_id: integer (nullable = true)
 |-- order_id: string (nullable = true)
 |-- order_date: date (nullable = true)
 |-- ship_date: date (nullable = true)
 |-- ship_mode: string (nullable = true)
 |-- customer_id: string (nullable = true)
 |-- customer_name: string (nullable = true)
 |-- segment: string (nullable = true)
 |-- country: string (nullable = true)
 |-- city: string (nullable = true)
 |-- state: string (nullable = true)
 |-- postal_code: integer (nullable = true)
 |-- region: string (nullable = true)
 |-- product_id: string (nullable = true)
 |-- category: string (nullable = true)
 |-- subcategory: string (nullable = true)
 |-- product_name: string (nullable = true)
 |-- sales: string (nullable = true)
 |-- quantity: double (nullable = true)
 |-- discount: double (nullable = true)
 |-- profit: double (nullable = true)

In [16]:
check_df.show(5)

+------+--------------+----------+----------+------------+-----------+---------------+---------+-------------+------------+---------+-----------+------+---------------+---------------+-----------+--------------------+------+--------+--------+-------+
|row_id|      order_id|order_date| ship_date|   ship_mode|customer_id|  customer_name|  segment|      country|        city|    state|postal_code|region|     product_id|       category|subcategory|        product_name| sales|quantity|discount| profit|
+------+--------------+----------+----------+------------+-----------+---------------+---------+-------------+------------+---------+-----------+------+---------------+---------------+-----------+--------------------+------+--------+--------+-------+
|   764|CA-2014-162775|2014-01-13|2014-01-15|Second Class|   CS-12250|Chris Selesnick|Corporate|United States|Bossier City|Louisiana|      71111| South|OFF-EN-10001990|Office Supplies|  Envelopes|     Staple envelope| 11.36|     2.0|     0.0| 5.3392|
|   765|CA-2014-162775|2014-01-13|2014-01-15|Second Class|   CS-12250|Chris Selesnick|Corporate|United States|Bossier City|Louisiana|      71111| South|OFF-EN-10001532|Office Supplies|  Envelopes|Brown Kraft Recyc...| 50.94|     3.0|     0.0|  25.47|
|   766|CA-2014-162775|2014-01-13|2014-01-15|Second Class|   CS-12250|Chris Selesnick|Corporate|United States|Bossier City|Louisiana|      71111| South|TEC-AC-10003174|     Technology|Accessories|Plantronics S12 C...|646.74|     6.0|     0.0|258.696|
|   767|CA-2014-162775|2014-01-13|2014-01-15|Second Class|   CS-12250|Chris Selesnick|Corporate|United States|Bossier City|Louisiana|      71111| South|OFF-BI-10004187|Office Supplies|    Binders|  3-ring staple pack|  5.64|     3.0|     0.0| 2.7072|
|   768|CA-2014-162775|2014-01-13|2014-01-15|Second Class|   CS-12250|Chris Selesnick|Corporate|United States|Bossier City|Louisiana|      71111| South|OFF-ST-10000025|Office Supplies|    Storage|Fellowes Stor/Dra...|572.58|     6.0|     0.0|34.3548|
+------+--------------+----------+----------+------------+-----------+---------------+---------+-------------+------------+---------+-----------+------+---------------+---------------+-----------+--------------------+------+--------+--------+-------+
only showing top 5 rows

In [ ]:
## result: write to bronze 
## double check the content of broze table