In [ ]:
# from delta import *
# from pyspark.sql import SparkSession

# builder = SparkSession.builder \
#     .appName("RetailPipeline") \
#     .config("spark.sql.extensions", "io.delta.sql.DeltaSparkSessionExtension") \
#     .config("spark.sql.catalog.spark_catalog", "org.apache.spark.sql.delta.catalog.DeltaCatalog")

# spark = configure_spark_with_delta_pip(builder).getOrCreate()

In [1]:
try:
    spark
except NameError:
    from pyspark.sql import SparkSession
    from delta import configure_spark_with_delta_pip

    builder = SparkSession.builder \
        .appName("retail_pipeline") \
        .master("local[*]") \
        .config("spark.sql.extensions", "io.delta.sql.DeltaSparkSessionExtension") \
        .config("spark.sql.catalog.spark_catalog", "org.apache.spark.sql.delta.catalog.DeltaCatalog")
    
    spark = configure_spark_with_delta_pip(builder).getOrCreate()

ERROR StatusLogger Reconfiguration failed: No configuration found for '5c29bfd' at 'null' in 'null'
ERROR StatusLogger Reconfiguration failed: No configuration found for 'Default' at 'null' in 'null'
26/04/23 16:25:01 WARN Utils: Your hostname, YTuSurface5 resolves to a loopback address: 127.0.1.1; using 10.255.255.254 instead (on interface lo)
26/04/23 16:25:01 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address

:: loading settings :: url = jar:file:/home/yiqingtu/spark/spark-3.5.5-bin-hadoop3/jars/ivy-2.5.1.jar!/org/apache/ivy/core/settings/ivysettings.xml

Ivy Default Cache set to: /home/yiqingtu/.ivy2/cache
The jars for the packages stored in: /home/yiqingtu/.ivy2/jars
io.delta#delta-spark_2.12 added as a dependency
:: resolving dependencies :: org.apache.spark#spark-submit-parent-8f9c44f2-1f8b-4fae-abbe-191c23be213c;1.0
	confs: [default]
	found io.delta#delta-spark_2.12;3.2.0 in central
	found io.delta#delta-storage;3.2.0 in central
	found org.antlr#antlr4-runtime;4.9.3 in central
:: resolution report :: resolve 190ms :: artifacts dl 12ms
	:: modules in use:
	io.delta#delta-spark_2.12;3.2.0 from central in [default]
	io.delta#delta-storage;3.2.0 from central in [default]
	org.antlr#antlr4-runtime;4.9.3 from central in [default]
	---------------------------------------------------------------------
	|                  |            modules            ||   artifacts   |
	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
	---------------------------------------------------------------------
	|      default     |   3   |   0   |   0   |   0   ||   3   |   0   |
	---------------------------------------------------------------------
:: retrieving :: org.apache.spark#spark-submit-parent-8f9c44f2-1f8b-4fae-abbe-191c23be213c
	confs: [default]
	0 artifacts copied, 3 already retrieved (0kB/6ms)
26/04/23 16:25:02 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
26/04/23 16:25:03 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.

In [30]:
bronze_orders_path = "../delta/bronze/orders"
df_bronze = spark.read.load(bronze_orders_path)

# need panda library
df_bronze.limit(1000).toPandas()

,row_id,order_id,order_date,ship_date,ship_mode,customer_id,customer_name,segment,country,city,...,postal_code,region,product_id,category,subcategory,product_name,sales,quantity,discount,profit
0,764,CA-2014-162775,2014-01-13,2014-01-15,Second Class,CS-12250,Chris Selesnick,Corporate,United States,Bossier City,...,71111,South,OFF-EN-10001990,Office Supplies,Envelopes,Staple envelope,11.36,2.0,0.0,5.3392
1,765,CA-2014-162775,2014-01-13,2014-01-15,Second Class,CS-12250,Chris Selesnick,Corporate,United States,Bossier City,...,71111,South,OFF-EN-10001532,Office Supplies,Envelopes,Brown Kraft Recycled Envelopes,50.94,3.0,0.0,25.4700
2,766,CA-2014-162775,2014-01-13,2014-01-15,Second Class,CS-12250,Chris Selesnick,Corporate,United States,Bossier City,...,71111,South,TEC-AC-10003174,Technology,Accessories,Plantronics S12 Corded Telephone Headset System,646.74,6.0,0.0,258.6960
3,767,CA-2014-162775,2014-01-13,2014-01-15,Second Class,CS-12250,Chris Selesnick,Corporate,United States,Bossier City,...,71111,South,OFF-BI-10004187,Office Supplies,Binders,3-ring staple pack,5.64,3.0,0.0,2.7072
4,768,CA-2014-162775,2014-01-13,2014-01-15,Second Class,CS-12250,Chris Selesnick,Corporate,United States,Bossier City,...,71111,South,OFF-ST-10000025,Office Supplies,Storage,Fellowes Stor/Drawer Steel Plus Storage Drawers,572.58,6.0,0.0,34.3548
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,6475,CA-2014-149524,2014-01-14,2014-01-15,First Class,BS-11590,Brendan Sweed,Corporate,United States,Philadelphia,...,19140,East,FUR-BO-10003433,Furniture,Bookcases,Sauder Cornerstone Collection Library,61.96,4.0,0.5,-53.2856
95,6475,CA-2014-149524,2014-01-14,2014-01-15,First Class,BS-11590,Brendan Sweed,Corporate,United States,Philadelphia,...,19140,East,FUR-BO-10003433,Furniture,Bookcases,Sauder Cornerstone Collection Library,61.96,4.0,0.5,-53.2856
96,717,CA-2014-130092,2014-01-11,2014-01-14,First Class,SV-20365,Seth Vernon,Consumer,United States,Dover,...,19901,East,FUR-FU-10000010,Furniture,Furnishings,"DAX Value U-Channel Document Frames, Easel Back",9.94,2.0,0.0,3.0814
97,717,CA-2014-130092,2014-01-11,2014-01-14,First Class,SV-20365,Seth Vernon,Consumer,United States,Dover,...,19901,East,FUR-FU-10000010,Furniture,Furnishings,"DAX Value U-Channel Document Frames, Easel Back",9.94,2.0,0.0,3.0814
98,717,CA-2014-130092,2014-01-11,2014-01-14,First Class,SV-20365,Seth Vernon,Consumer,United States,Dover,...,19901,East,FUR-FU-10000010,Furniture,Furnishings,"DAX Value U-Channel Document Frames, Easel Back",9.94,2.0,0.0,3.0814

In [3]:
df_bronze.printSchema()

root
 |-- row_id: integer (nullable = true)
 |-- order_id: string (nullable = true)
 |-- order_date: date (nullable = true)
 |-- ship_date: date (nullable = true)
 |-- ship_mode: string (nullable = true)
 |-- customer_id: string (nullable = true)
 |-- customer_name: string (nullable = true)
 |-- segment: string (nullable = true)
 |-- country: string (nullable = true)
 |-- city: string (nullable = true)
 |-- state: string (nullable = true)
 |-- postal_code: integer (nullable = true)
 |-- region: string (nullable = true)
 |-- product_id: string (nullable = true)
 |-- category: string (nullable = true)
 |-- subcategory: string (nullable = true)
 |-- product_name: string (nullable = true)
 |-- sales: string (nullable = true)
 |-- quantity: double (nullable = true)
 |-- discount: double (nullable = true)
 |-- profit: double (nullable = true)

In [6]:
from pyspark.sql.functions import col
df_bronze = df_bronze \
    .withColumn("sales", col("sales").cast("double")) \
    .withColumn("quantity", col("quantity").cast("int"))

In [8]:
df_bronze.filter(
    col("sales").isNull() | col("profit").isNull()
).show()

+------+--------------+----------+----------+--------------+-----------+-------------+--------+-------------+-------+-----+-----------+-------+---------------+---------------+-----------+--------------------+-----+--------+--------+------+
|row_id|      order_id|order_date| ship_date|     ship_mode|customer_id|customer_name| segment|      country|   city|state|postal_code| region|     product_id|       category|subcategory|        product_name|sales|quantity|discount|profit|
+------+--------------+----------+----------+--------------+-----------+-------------+--------+-------------+-------+-----+-----------+-------+---------------+---------------+-----------+--------------------+-----+--------+--------+------+
|  7981|CA-2014-103800|2014-01-03|2014-01-07|Standard Class|   DP-13000|Darren Powers|Consumer|United States|Houston|Texas|      77095|Central|OFF-PA-10000174|Office Supplies|      Paper|"Message Book, Wi...| NULL|      16|     2.0|   0.2|
|  7981|CA-2014-103800|2014-01-03|2014-01-07|Standard Class|   DP-13000|Darren Powers|Consumer|United States|Houston|Texas|      77095|Central|OFF-PA-10000174|Office Supplies|      Paper|"Message Book, Wi...| NULL|      16|     2.0|   0.2|
|  7981|CA-2014-103800|2014-01-03|2014-01-07|Standard Class|   DP-13000|Darren Powers|Consumer|United States|Houston|Texas|      77095|Central|OFF-PA-10000174|Office Supplies|      Paper|"Message Book, Wi...| NULL|      16|     2.0|   0.2|
+------+--------------+----------+----------+--------------+-----------+-------------+--------+-------------+-------+-----+-----------+-------+---------------+---------------+-----------+--------------------+-----+--------+--------+------+

In [10]:
# how many null

df_bronze.filter(col("sales").isNull()).count()

3

In [13]:
# drop null and repeat records

# For business: customer_id is required for downstream customer analytics
df_bronze = df_bronze.filter(col("sales").isNotNull())

In [14]:
# step 2 remove duplicate

from pyspark.sql.functions import count

df_bronze.groupBy("order_id") \
    .count() \
    .filter("count > 1") \
    .show()

+--------------+-----+
|      order_id|count|
+--------------+-----+
|CA-2014-118192|    6|
|CA-2014-109232|    3|
|CA-2014-162775|   15|
|CA-2014-157147|    9|
|CA-2014-130813|    3|
|CA-2014-106054|    3|
|CA-2014-167199|   21|
|CA-2014-105417|    6|
|CA-2014-112326|    9|
|CA-2014-149020|    6|
|CA-2014-135405|    6|
|CA-2014-141817|    3|
|CA-2014-149524|    3|
|CA-2014-130092|    3|
+--------------+-----+

In [15]:
df_bronze.count() - df_bronze.dropDuplicates().count()

64

In [16]:
total = df_bronze.count()
distinct = df_bronze.distinct().count()

print("Duplicate rows:", total - distinct)

Duplicate rows: 64

In [20]:
df_bronze.groupBy(df_bronze.columns) \
    .count() \
    .filter("count > 1") \
    .show(100)

+------+--------------+----------+----------+--------------+-----------+-----------------+-----------+-------------+--------------+--------------+-----------+-------+---------------+---------------+-----------+--------------------+-------+--------+--------+--------+-----+
|row_id|      order_id|order_date| ship_date|     ship_mode|customer_id|    customer_name|    segment|      country|          city|         state|postal_code| region|     product_id|       category|subcategory|        product_name|  sales|quantity|discount|  profit|count|
+------+--------------+----------+----------+--------------+-----------+-----------------+-----------+-------------+--------------+--------------+-----------+-------+---------------+---------------+-----------+--------------------+-------+--------+--------+--------+-----+
|  9629|CA-2014-118192|2014-01-13|2014-01-18|Standard Class|   MM-17920|    Michael Moore|   Consumer|United States|        Newark|          Ohio|      43055|   East|OFF-PA-10002947|Office Supplies|      Paper|          Xerox 1923| 37.408|       7|     0.2| 13.0928|    3|
|   764|CA-2014-162775|2014-01-13|2014-01-15|  Second Class|   CS-12250|  Chris Selesnick|  Corporate|United States|  Bossier City|     Louisiana|      71111|  South|OFF-EN-10001990|Office Supplies|  Envelopes|     Staple envelope|  11.36|       2|     0.0|  5.3392|    3|
|  4938|CA-2014-157147|2014-01-13|2014-01-18|Standard Class|   BD-11605|     Brian Dahlen|   Consumer|United States| San Francisco|    California|      94109|   West|OFF-ST-10000078|Office Supplies|    Storage|Tennsco 6- and 18...|1325.85|       5|     0.0| 238.653|    3|
|   767|CA-2014-162775|2014-01-13|2014-01-15|  Second Class|   CS-12250|  Chris Selesnick|  Corporate|United States|  Bossier City|     Louisiana|      71111|  South|OFF-BI-10004187|Office Supplies|    Binders|  3-ring staple pack|   5.64|       3|     0.0|  2.7072|    3|
|  2979|CA-2014-109232|2014-01-13|2014-01-16|  Second Class|   ND-18370|Natalie DeCherney|   Consumer|United States|Mount Pleasant|South Carolina|      29464|  South|FUR-CH-10000422|      Furniture|     Chairs|Global Highback L...| 545.94|       6|     0.0| 87.3504|    3|
|   766|CA-2014-162775|2014-01-13|2014-01-15|  Second Class|   CS-12250|  Chris Selesnick|  Corporate|United States|  Bossier City|     Louisiana|      71111|  South|TEC-AC-10003174|     Technology|Accessories|Plantronics S12 C...| 646.74|       6|     0.0| 258.696|    3|
|  4939|CA-2014-157147|2014-01-13|2014-01-18|Standard Class|   BD-11605|     Brian Dahlen|   Consumer|United States| San Francisco|    California|      94109|   West|FUR-BO-10003034|      Furniture|  Bookcases|O'Sullivan Elevat...|333.999|       3|    0.15|  3.9294|    3|
|   765|CA-2014-162775|2014-01-13|2014-01-15|  Second Class|   CS-12250|  Chris Selesnick|  Corporate|United States|  Bossier City|     Louisiana|      71111|  South|OFF-EN-10001532|Office Supplies|  Envelopes|Brown Kraft Recyc...|  50.94|       3|     0.0|   25.47|    3|
|   768|CA-2014-162775|2014-01-13|2014-01-15|  Second Class|   CS-12250|  Chris Selesnick|  Corporate|United States|  Bossier City|     Louisiana|      71111|  South|OFF-ST-10000025|Office Supplies|    Storage|Fellowes Stor/Dra...| 572.58|       6|     0.0| 34.3548|    3|
|  4940|CA-2014-157147|2014-01-13|2014-01-18|Standard Class|   BD-11605|     Brian Dahlen|   Consumer|United States| San Francisco|    California|      94109|   West|OFF-AR-10003514|Office Supplies|        Art|4009 Highlighters...|   19.9|       5|     0.0|   6.567|    3|
|  9630|CA-2014-118192|2014-01-13|2014-01-18|Standard Class|   MM-17920|    Michael Moore|   Consumer|United States|        Newark|          Ohio|      43055|   East|OFF-BI-10003476|Office Supplies|    Binders|Avery Metallic Po...|  3.438|       2|     0.7| -2.5212|    3|
|  7480|CA-2014-167199|2014-01-06|2014-01-10|Standard Class|   ME-17320|    Maria Etezadi|Home Office|United States|     Henderson|      Kentucky|      42420|  South|OFF-FA-10001883|Office Supplies|  Fasteners|Alliance Super-Si...|  31.12|       4|     0.0|  0.3112|    3|
|  7478|CA-2014-167199|2014-01-06|2014-01-10|Standard Class|   ME-17320|    Maria Etezadi|Home Office|United States|     Henderson|      Kentucky|      42420|  South|TEC-PH-10004977|     Technology|     Phones|         GE 30524EE4| 391.98|       2|     0.0|113.6742|    3|
|  5328|CA-2014-130813|2014-01-06|2014-01-08|  Second Class|   LS-17230| Lycoris Saunders|   Consumer|United States|   Los Angeles|    California|      90049|   West|OFF-PA-10002005|Office Supplies|      Paper|           Xerox 225|  19.44|       3|     0.0|  9.3312|    3|
|  7475|CA-2014-167199|2014-01-06|2014-01-10|Standard Class|   ME-17320|    Maria Etezadi|Home Office|United States|     Henderson|      Kentucky|      42420|  South|FUR-CH-10004063|      Furniture|     Chairs|Global Deluxe Hig...|2573.82|       9|     0.0|746.4078|    3|
|  7476|CA-2014-167199|2014-01-06|2014-01-10|Standard Class|   ME-17320|    Maria Etezadi|Home Office|United States|     Henderson|      Kentucky|      42420|  South|OFF-BI-10004632|Office Supplies|    Binders|Ibico Hi-Tech Man...| 609.98|       2|     0.0| 274.491|    3|
|  7479|CA-2014-167199|2014-01-06|2014-01-10|Standard Class|   ME-17320|    Maria Etezadi|Home Office|United States|     Henderson|      Kentucky|      42420|  South|TEC-PH-10004539|     Technology|     Phones|Wireless Extender...| 755.96|       4|     0.0|204.1092|    3|
|  7181|CA-2014-106054|2014-01-06|2014-01-07|   First Class|   JO-15145|    Jack O'Briant|  Corporate|United States|        Athens|       Georgia|      30605|  South|OFF-AR-10002399|Office Supplies|        Art|Dixon Prang Water...|  12.78|       3|     0.0|  5.2398|    3|
|  7477|CA-2014-167199|2014-01-06|2014-01-10|Standard Class|   ME-17320|    Maria Etezadi|Home Office|United States|     Henderson|      Kentucky|      42420|  South|OFF-AR-10001662|Office Supplies|        Art|Rogers Handheld B...|   5.48|       2|     0.0|  1.4796|    3|
|  7481|CA-2014-167199|2014-01-06|2014-01-10|Standard Class|   ME-17320|    Maria Etezadi|Home Office|United States|     Henderson|      Kentucky|      42420|  South|OFF-PA-10000955|Office Supplies|      Paper|Southworth 25% Co...|   6.54|       1|     0.0|  3.0084|    3|
|  7661|CA-2014-105417|2014-01-07|2014-01-12|Standard Class|   VS-21820| Vivek Sundaresam|   Consumer|United States|    Huntsville|         Texas|      77340|Central|FUR-FU-10004864|      Furniture|Furnishings|"Howard Miller 14...| 76.728|       3|     0.6|-53.7096|    3|
|  7662|CA-2014-105417|2014-01-07|2014-01-12|Standard Class|   VS-21820| Vivek Sundaresam|   Consumer|United States|    Huntsville|         Texas|      77340|Central|OFF-BI-10003708|Office Supplies|    Binders|Acco Four Pocket ...|  10.43|       7|     0.8|-18.2525|    3|
|   740|CA-2014-112326|2014-01-04|2014-01-08|Standard Class|   PO-19195|    Phillina Ober|Home Office|United States|    Naperville|      Illinois|      60540|Central|OFF-LA-10003223|Office Supplies|     Labels|           Avery 508| 11.784|       3|     0.2|  4.2717|    3|
|   741|CA-2014-112326|2014-01-04|2014-01-08|Standard Class|   PO-19195|    Phillina Ober|Home Office|United States|    Naperville|      Illinois|      60540|Central|OFF-ST-10002743|Office Supplies|    Storage|SAFCO Boltless St...|272.736|       3|     0.2|-64.7748|    3|
|   742|CA-2014-112326|2014-01-04|2014-01-08|Standard Class|   PO-19195|    Phillina Ober|Home Office|United States|    Naperville|      Illinois|      60540|Central|OFF-BI-10004094|Office Supplies|    Binders|GBC Standard Plas...|   3.54|       2|     0.8|  -5.487|    3|
|   867|CA-2014-149020|2014-01-10|2014-01-15|Standard Class|   AJ-10780|   Anthony Jacobs|  Corporate|United States|   Springfield|      Virginia|      22153|  South|FUR-FU-10000965|      Furniture|Furnishings|"Howard Miller 11...|  51.94|       1|     0.0| 21.2954|    3|
|   866|CA-2014-149020|2014-01-10|2014-01-15|Standard Class|   AJ-10780|   Anthony Jacobs|  Corporate|United States|   Springfield|      Virginia|      22153|  South|OFF-LA-10004272|Office Supplies|     Labels|           Avery 482|   2.89|       1|     0.0|  1.3583|    3|
|   593|CA-2014-135405|2014-01-09|2014-01-13|Standard Class|   MS-17830|    Melanie Seite|   Consumer|United States|        Laredo|         Texas|      78041|Central|OFF-AR-10004078|Office Supplies|        Art|          Newell 312|  9.344|       2|     0.2|   1.168|    3|
|   594|CA-2014-135405|2014-01-09|2014-01-13|Standard Class|   MS-17830|    Melanie Seite|   Consumer|United States|        Laredo|         Texas|      78041|Central|TEC-AC-10001266|     Technology|Accessories|Memorex Micro Tra...|   31.2|       3|     0.2|    9.75|    3|
|  1760|CA-2014-141817|2014-01-05|2014-01-12|Standard Class|   MB-18085|       Mick Brown|   Consumer|United States|  Philadelphia|  Pennsylvania|      19143|   East|OFF-AR-10003478|Office Supplies|        Art|Avery Hi-Liter Ev...| 19.536|       3|     0.2|   4.884|    3|
|  6475|CA-2014-149524|2014-01-14|2014-01-15|   First Class|   BS-11590|    Brendan Sweed|  Corporate|United States|  Philadelphia|  Pennsylvania|      19140|   East|FUR-BO-10003433|      Furniture|  Bookcases|Sauder Cornerston...|  61.96|       4|     0.5|-53.2856|    3|
|   717|CA-2014-130092|2014-01-11|2014-01-14|   First Class|   SV-20365|      Seth Vernon|   Consumer|United States|         Dover|      Delaware|      19901|   East|FUR-FU-10000010|      Furniture|Furnishings|DAX Value U-Chann...|   9.94|       2|     0.0|  3.0814|    3|
+------+--------------+----------+----------+--------------+-----------+-----------------+-----------+-------------+--------------+--------------+-----------+-------+---------------+---------------+-----------+--------------------+-------+--------+--------+--------+-----+

In [21]:
# produce report
row_dupes_df = df_bronze.groupBy(df_bronze.columns) \
    .count() \
    .filter(col("count") > 1)

In [22]:
row_duplicates = df_bronze.join(
    row_dupes_df.drop("count"),
    on=df_bronze.columns,
    how="inner"
)

In [23]:
row_duplicates.write.format("delta") \
    .mode("overwrite") \
    .saveAsTable("row_level_duplicates")

26/04/23 17:00:49 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 95.00% for 8 writers
26/04/23 17:00:49 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 84.44% for 9 writers
26/04/23 17:00:49 WARN MemoryManager: Total allocation exceeds 95.00% (1,020,054,720 bytes) of heap memory
Scaling row group sizes to 95.00% for 8 writers

In [25]:
row_duplicates.count()

96

In [28]:
row_duplicates.limit(10).toPandas()

,row_id,order_id,order_date,ship_date,ship_mode,customer_id,customer_name,segment,country,city,...,postal_code,region,product_id,category,subcategory,product_name,sales,quantity,discount,profit
0,764,CA-2014-162775,2014-01-13,2014-01-15,Second Class,CS-12250,Chris Selesnick,Corporate,United States,Bossier City,...,71111,South,OFF-EN-10001990,Office Supplies,Envelopes,Staple envelope,11.360,2,0.00,5.3392
1,765,CA-2014-162775,2014-01-13,2014-01-15,Second Class,CS-12250,Chris Selesnick,Corporate,United States,Bossier City,...,71111,South,OFF-EN-10001532,Office Supplies,Envelopes,Brown Kraft Recycled Envelopes,50.940,3,0.00,25.4700
2,766,CA-2014-162775,2014-01-13,2014-01-15,Second Class,CS-12250,Chris Selesnick,Corporate,United States,Bossier City,...,71111,South,TEC-AC-10003174,Technology,Accessories,Plantronics S12 Corded Telephone Headset System,646.740,6,0.00,258.6960
3,767,CA-2014-162775,2014-01-13,2014-01-15,Second Class,CS-12250,Chris Selesnick,Corporate,United States,Bossier City,...,71111,South,OFF-BI-10004187,Office Supplies,Binders,3-ring staple pack,5.640,3,0.00,2.7072
4,768,CA-2014-162775,2014-01-13,2014-01-15,Second Class,CS-12250,Chris Selesnick,Corporate,United States,Bossier City,...,71111,South,OFF-ST-10000025,Office Supplies,Storage,Fellowes Stor/Drawer Steel Plus Storage Drawers,572.580,6,0.00,34.3548
5,2979,CA-2014-109232,2014-01-13,2014-01-16,Second Class,ND-18370,Natalie DeCherney,Consumer,United States,Mount Pleasant,...,29464,South,FUR-CH-10000422,Furniture,Chairs,Global Highback Leather Tilter in Burgundy,545.940,6,0.00,87.3504
6,4938,CA-2014-157147,2014-01-13,2014-01-18,Standard Class,BD-11605,Brian Dahlen,Consumer,United States,San Francisco,...,94109,West,OFF-ST-10000078,Office Supplies,Storage,Tennsco 6- and 18-Compartment Lockers,1325.850,5,0.00,238.6530
7,4939,CA-2014-157147,2014-01-13,2014-01-18,Standard Class,BD-11605,Brian Dahlen,Consumer,United States,San Francisco,...,94109,West,FUR-BO-10003034,Furniture,Bookcases,"O'Sullivan Elevations Bookcase, Cherry Finish",333.999,3,0.15,3.9294
8,4940,CA-2014-157147,2014-01-13,2014-01-18,Standard Class,BD-11605,Brian Dahlen,Consumer,United States,San Francisco,...,94109,West,OFF-AR-10003514,Office Supplies,Art,4009 Highlighters by Sanford,19.900,5,0.00,6.5670
9,9629,CA-2014-118192,2014-01-13,2014-01-18,Standard Class,MM-17920,Michael Moore,Consumer,United States,Newark,...,43055,East,OFF-PA-10002947,Office Supplies,Paper,Xerox 1923,37.408,7,0.20,13.0928

In [ ]:
# done extract duplicate

# ttd
#    extract key level
#    clean up 


# add structure in markdown


# section 1: read
# section: clean data
# section: deduplicate

# section: check business rule
# section: write silver

In [31]:
# Business check: sales must be >= 0 because refunds are stored separately
df_bronze.filter("sales <= 0").count()

0

26/04/24 12:42:54 WARN HeartbeatReceiver: Removing executor driver with no recent heartbeats: 24666146 ms exceeds timeout 120000 ms
26/04/24 12:42:54 WARN SparkContext: Killing executors is not supported by current scheduler.
26/04/24 12:49:50 ERROR Inbox: Ignoring error
org.apache.spark.SparkException: Exception thrown in awaitResult:
	at org.apache.spark.util.SparkThreadUtils$.awaitResult(SparkThreadUtils.scala:56)
	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:310)
	at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
	at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:102)
	at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:110)
	at org.apache.spark.util.RpcUtils$.makeDriverRef(RpcUtils.scala:36)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.driverEndpoint$lzycompute(BlockManagerMasterEndpoint.scala:124)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.org$apache$spark$storage$BlockManagerMasterEndpoint$$driverEndpoint(BlockManagerMasterEndpoint.scala:123)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.isExecutorAlive$lzycompute$1(BlockManagerMasterEndpoint.scala:688)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.isExecutorAlive$1(BlockManagerMasterEndpoint.scala:687)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.org$apache$spark$storage$BlockManagerMasterEndpoint$$register(BlockManagerMasterEndpoint.scala:725)
	at org.apache.spark.storage.BlockManagerMasterEndpoint$$anonfun$receiveAndReply$1.applyOrElse(BlockManagerMasterEndpoint.scala:133)
	at org.apache.spark.rpc.netty.Inbox.$anonfun$process$1(Inbox.scala:103)
	at org.apache.spark.rpc.netty.Inbox.safelyCall(Inbox.scala:213)
	at org.apache.spark.rpc.netty.Inbox.process(Inbox.scala:100)
	at org.apache.spark.rpc.netty.MessageLoop.org$apache$spark$rpc$netty$MessageLoop$$receiveLoop(MessageLoop.scala:75)
	at org.apache.spark.rpc.netty.MessageLoop$$anon$1.run(MessageLoop.scala:41)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.apache.spark.rpc.RpcEndpointNotFoundException: Cannot find endpoint: spark://CoarseGrainedScheduler@10.255.255.254:36601
	at org.apache.spark.rpc.netty.NettyRpcEnv.$anonfun$asyncSetupEndpointRefByURI$1(NettyRpcEnv.scala:148)
	at org.apache.spark.rpc.netty.NettyRpcEnv.$anonfun$asyncSetupEndpointRefByURI$1$adapted(NettyRpcEnv.scala:144)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at org.apache.spark.util.ThreadUtils$$anon$1.execute(ThreadUtils.scala:99)
	at scala.concurrent.impl.ExecutionContextImpl$$anon$4.execute(ExecutionContextImpl.scala:138)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:72)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1(Promise.scala:288)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1$adapted(Promise.scala:288)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:288)
	at scala.concurrent.Promise.complete(Promise.scala:53)
	at scala.concurrent.Promise.complete$(Promise.scala:52)
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:187)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at org.apache.spark.util.ThreadUtils$$anon$1.execute(ThreadUtils.scala:99)
	at scala.concurrent.impl.ExecutionContextImpl$$anon$4.execute(ExecutionContextImpl.scala:138)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:72)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1(Promise.scala:288)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1$adapted(Promise.scala:288)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:288)
	at scala.concurrent.Promise.complete(Promise.scala:53)
	at scala.concurrent.Promise.complete$(Promise.scala:52)
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:187)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at scala.concurrent.BatchingExecutor$Batch.processBatch$1(BatchingExecutor.scala:67)
	at scala.concurrent.BatchingExecutor$Batch.$anonfun$run$1(BatchingExecutor.scala:82)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
	at scala.concurrent.BatchingExecutor$Batch.run(BatchingExecutor.scala:59)
	at scala.concurrent.Future$InternalCallbackExecutor$.unbatchedExecute(Future.scala:875)
	at scala.concurrent.BatchingExecutor.execute(BatchingExecutor.scala:110)
	at scala.concurrent.BatchingExecutor.execute$(BatchingExecutor.scala:107)
	at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:873)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:72)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1(Promise.scala:288)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1$adapted(Promise.scala:288)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:288)
	at scala.concurrent.Promise.trySuccess(Promise.scala:94)
	at scala.concurrent.Promise.trySuccess$(Promise.scala:94)
	at scala.concurrent.impl.Promise$DefaultPromise.trySuccess(Promise.scala:187)
	at org.apache.spark.rpc.netty.NettyRpcEnv.onSuccess$1(NettyRpcEnv.scala:225)
	at org.apache.spark.rpc.netty.NettyRpcEnv.$anonfun$askAbortable$5(NettyRpcEnv.scala:239)
	at org.apache.spark.rpc.netty.NettyRpcEnv.$anonfun$askAbortable$5$adapted(NettyRpcEnv.scala:238)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at org.apache.spark.util.ThreadUtils$$anon$1.execute(ThreadUtils.scala:99)
	at scala.concurrent.impl.ExecutionContextImpl$$anon$4.execute(ExecutionContextImpl.scala:138)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:72)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1(Promise.scala:288)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1$adapted(Promise.scala:288)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:288)
	at scala.concurrent.Promise.complete(Promise.scala:53)
	at scala.concurrent.Promise.complete$(Promise.scala:52)
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:187)
	at scala.concurrent.Promise.success(Promise.scala:86)
	at scala.concurrent.Promise.success$(Promise.scala:86)
	at scala.concurrent.impl.Promise$DefaultPromise.success(Promise.scala:187)
	at org.apache.spark.rpc.netty.LocalNettyRpcCallContext.send(NettyRpcCallContext.scala:50)
	at org.apache.spark.rpc.netty.NettyRpcCallContext.reply(NettyRpcCallContext.scala:32)
	at org.apache.spark.rpc.netty.RpcEndpointVerifier$$anonfun$receiveAndReply$1.applyOrElse(RpcEndpointVerifier.scala:31)
	... 8 more
26/04/24 12:49:50 WARN Executor: Issue communicating with driver in heartbeater
org.apache.spark.SparkException: Exception thrown in awaitResult:
	at org.apache.spark.util.SparkThreadUtils$.awaitResult(SparkThreadUtils.scala:56)
	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:310)
	at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
	at org.apache.spark.rpc.RpcEndpointRef.askSync(RpcEndpointRef.scala:101)
	at org.apache.spark.rpc.RpcEndpointRef.askSync(RpcEndpointRef.scala:85)
	at org.apache.spark.storage.BlockManagerMaster.registerBlockManager(BlockManagerMaster.scala:80)
	at org.apache.spark.storage.BlockManager.reregister(BlockManager.scala:642)
	at org.apache.spark.executor.Executor.reportHeartBeat(Executor.scala:1223)
	at org.apache.spark.executor.Executor.$anonfun$heartbeater$1(Executor.scala:295)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:1928)
	at org.apache.spark.Heartbeater$$anon$1.run(Heartbeater.scala:46)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.apache.spark.SparkException: Exception thrown in awaitResult:
	at org.apache.spark.util.SparkThreadUtils$.awaitResult(SparkThreadUtils.scala:56)
	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:310)
	at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
	at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:102)
	at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:110)
	at org.apache.spark.util.RpcUtils$.makeDriverRef(RpcUtils.scala:36)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.driverEndpoint$lzycompute(BlockManagerMasterEndpoint.scala:124)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.org$apache$spark$storage$BlockManagerMasterEndpoint$$driverEndpoint(BlockManagerMasterEndpoint.scala:123)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.isExecutorAlive$lzycompute$1(BlockManagerMasterEndpoint.scala:688)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.isExecutorAlive$1(BlockManagerMasterEndpoint.scala:687)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.org$apache$spark$storage$BlockManagerMasterEndpoint$$register(BlockManagerMasterEndpoint.scala:725)
	at org.apache.spark.storage.BlockManagerMasterEndpoint$$anonfun$receiveAndReply$1.applyOrElse(BlockManagerMasterEndpoint.scala:133)
	at org.apache.spark.rpc.netty.Inbox.$anonfun$process$1(Inbox.scala:103)
	at org.apache.spark.rpc.netty.Inbox.safelyCall(Inbox.scala:213)
	at org.apache.spark.rpc.netty.Inbox.process(Inbox.scala:100)
	at org.apache.spark.rpc.netty.MessageLoop.org$apache$spark$rpc$netty$MessageLoop$$receiveLoop(MessageLoop.scala:75)
	at org.apache.spark.rpc.netty.MessageLoop$$anon$1.run(MessageLoop.scala:41)
	... 3 more
Caused by: org.apache.spark.rpc.RpcEndpointNotFoundException: Cannot find endpoint: spark://CoarseGrainedScheduler@10.255.255.254:36601
	at org.apache.spark.rpc.netty.NettyRpcEnv.$anonfun$asyncSetupEndpointRefByURI$1(NettyRpcEnv.scala:148)
	at org.apache.spark.rpc.netty.NettyRpcEnv.$anonfun$asyncSetupEndpointRefByURI$1$adapted(NettyRpcEnv.scala:144)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at org.apache.spark.util.ThreadUtils$$anon$1.execute(ThreadUtils.scala:99)
	at scala.concurrent.impl.ExecutionContextImpl$$anon$4.execute(ExecutionContextImpl.scala:138)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:72)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1(Promise.scala:288)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1$adapted(Promise.scala:288)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:288)
	at scala.concurrent.Promise.complete(Promise.scala:53)
	at scala.concurrent.Promise.complete$(Promise.scala:52)
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:187)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at org.apache.spark.util.ThreadUtils$$anon$1.execute(ThreadUtils.scala:99)
	at scala.concurrent.impl.ExecutionContextImpl$$anon$4.execute(ExecutionContextImpl.scala:138)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:72)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1(Promise.scala:288)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1$adapted(Promise.scala:288)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:288)
	at scala.concurrent.Promise.complete(Promise.scala:53)
	at scala.concurrent.Promise.complete$(Promise.scala:52)
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:187)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at scala.concurrent.BatchingExecutor$Batch.processBatch$1(BatchingExecutor.scala:67)
	at scala.concurrent.BatchingExecutor$Batch.$anonfun$run$1(BatchingExecutor.scala:82)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
	at scala.concurrent.BatchingExecutor$Batch.run(BatchingExecutor.scala:59)
	at scala.concurrent.Future$InternalCallbackExecutor$.unbatchedExecute(Future.scala:875)
	at scala.concurrent.BatchingExecutor.execute(BatchingExecutor.scala:110)
	at scala.concurrent.BatchingExecutor.execute$(BatchingExecutor.scala:107)
	at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:873)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:72)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1(Promise.scala:288)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1$adapted(Promise.scala:288)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:288)
	at scala.concurrent.Promise.trySuccess(Promise.scala:94)
	at scala.concurrent.Promise.trySuccess$(Promise.scala:94)
	at scala.concurrent.impl.Promise$DefaultPromise.trySuccess(Promise.scala:187)
	at org.apache.spark.rpc.netty.NettyRpcEnv.onSuccess$1(NettyRpcEnv.scala:225)
	at org.apache.spark.rpc.netty.NettyRpcEnv.$anonfun$askAbortable$5(NettyRpcEnv.scala:239)
	at org.apache.spark.rpc.netty.NettyRpcEnv.$anonfun$askAbortable$5$adapted(NettyRpcEnv.scala:238)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at org.apache.spark.util.ThreadUtils$$anon$1.execute(ThreadUtils.scala:99)
	at scala.concurrent.impl.ExecutionContextImpl$$anon$4.execute(ExecutionContextImpl.scala:138)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:72)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1(Promise.scala:288)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1$adapted(Promise.scala:288)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:288)
	at scala.concurrent.Promise.complete(Promise.scala:53)
	at scala.concurrent.Promise.complete$(Promise.scala:52)
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:187)
	at scala.concurrent.Promise.success(Promise.scala:86)
	at scala.concurrent.Promise.success$(Promise.scala:86)
	at scala.concurrent.impl.Promise$DefaultPromise.success(Promise.scala:187)
	at org.apache.spark.rpc.netty.LocalNettyRpcCallContext.send(NettyRpcCallContext.scala:50)
	at org.apache.spark.rpc.netty.NettyRpcCallContext.reply(NettyRpcCallContext.scala:32)
	at org.apache.spark.rpc.netty.RpcEndpointVerifier$$anonfun$receiveAndReply$1.applyOrElse(RpcEndpointVerifier.scala:31)
	... 8 more
26/04/24 12:50:00 ERROR Inbox: Ignoring error
org.apache.spark.SparkException: Exception thrown in awaitResult:
	at org.apache.spark.util.SparkThreadUtils$.awaitResult(SparkThreadUtils.scala:56)
	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:310)
	at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
	at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:102)
	at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:110)
	at org.apache.spark.util.RpcUtils$.makeDriverRef(RpcUtils.scala:36)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.driverEndpoint$lzycompute(BlockManagerMasterEndpoint.scala:124)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.org$apache$spark$storage$BlockManagerMasterEndpoint$$driverEndpoint(BlockManagerMasterEndpoint.scala:123)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.isExecutorAlive$lzycompute$1(BlockManagerMasterEndpoint.scala:688)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.isExecutorAlive$1(BlockManagerMasterEndpoint.scala:687)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.org$apache$spark$storage$BlockManagerMasterEndpoint$$register(BlockManagerMasterEndpoint.scala:725)
	at org.apache.spark.storage.BlockManagerMasterEndpoint$$anonfun$receiveAndReply$1.applyOrElse(BlockManagerMasterEndpoint.scala:133)
	at org.apache.spark.rpc.netty.Inbox.$anonfun$process$1(Inbox.scala:103)
	at org.apache.spark.rpc.netty.Inbox.safelyCall(Inbox.scala:213)
	at org.apache.spark.rpc.netty.Inbox.process(Inbox.scala:100)
	at org.apache.spark.rpc.netty.MessageLoop.org$apache$spark$rpc$netty$MessageLoop$$receiveLoop(MessageLoop.scala:75)
	at org.apache.spark.rpc.netty.MessageLoop$$anon$1.run(MessageLoop.scala:41)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.apache.spark.rpc.RpcEndpointNotFoundException: Cannot find endpoint: spark://CoarseGrainedScheduler@10.255.255.254:36601
	at org.apache.spark.rpc.netty.NettyRpcEnv.$anonfun$asyncSetupEndpointRefByURI$1(NettyRpcEnv.scala:148)
	at org.apache.spark.rpc.netty.NettyRpcEnv.$anonfun$asyncSetupEndpointRefByURI$1$adapted(NettyRpcEnv.scala:144)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at org.apache.spark.util.ThreadUtils$$anon$1.execute(ThreadUtils.scala:99)
	at scala.concurrent.impl.ExecutionContextImpl$$anon$4.execute(ExecutionContextImpl.scala:138)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:72)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1(Promise.scala:288)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1$adapted(Promise.scala:288)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:288)
	at scala.concurrent.Promise.complete(Promise.scala:53)
	at scala.concurrent.Promise.complete$(Promise.scala:52)
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:187)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at org.apache.spark.util.ThreadUtils$$anon$1.execute(ThreadUtils.scala:99)
	at scala.concurrent.impl.ExecutionContextImpl$$anon$4.execute(ExecutionContextImpl.scala:138)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:72)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1(Promise.scala:288)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1$adapted(Promise.scala:288)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:288)
	at scala.concurrent.Promise.complete(Promise.scala:53)
	at scala.concurrent.Promise.complete$(Promise.scala:52)
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:187)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at scala.concurrent.BatchingExecutor$Batch.processBatch$1(BatchingExecutor.scala:67)